<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Manju12Yadav" failures="1" tests="4" name="com.menu_module.AddMenuTest" time="9.092" errors="0" timestamp="2023-03-29T17:29:52 IST" skipped="3">
  <testcase classname="com.menu_module.AddMenuTest" name="addMenu" time="2.250">
    <skipped/>
  </testcase> <!-- addMenu -->
  <system-out>
    <![CDATA[addMenu--------> TestScript Execution Started
TestScript execution Skipped]]>
  </system-out>
  <testcase classname="com.menu_module.AddMenuTest" name="addMenu" time="2.255">
    <skipped/>
  </testcase> <!-- addMenu -->
  <system-out>
    <![CDATA[addMenu--------> TestScript Execution Started
TestScript execution Skipped]]>
  </system-out>
  <testcase classname="com.menu_module.AddMenuTest" name="addMenu" time="2.384">
    <skipped/>
  </testcase> <!-- addMenu -->
  <system-out>
    <![CDATA[addMenu--------> TestScript Execution Started
TestScript execution Skipped]]>
  </system-out>
  <testcase classname="com.menu_module.AddMenuTest" name="addMenu" time="2.203">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.menu_module.AddMenuTest.addMenu(AddMenuTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- addMenu -->
  <system-out>
    <![CDATA[addMenu--------> TestScript Execution Started
TestScripts Execution Failed]]>
  </system-out>
</testsuite> <!-- com.menu_module.AddMenuTest -->
